version: "3.9"
services:
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
  node:
    build: 
      dockerfile: ./docker/node/Dockerfile
      args:
        git_repo: ${GIT_REPO}
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "${NODE_APP_DEFAULT_LINK}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  spring-boot:
    build: 
      dockerfile:  ./docker/java/Dockerfile
      args:
        jar_file_name: ${JAR_FILE_NAME}
        conf_file: ${CONF_FILE}
        git_repo: ${GIT_REPO}
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      node:
        condition: service_healthy